FROM registry.digitalservice.id/proxyjds/library/node:16.13.2-alpine3.15

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG BASE_URL
ARG GOOGLE_ANALYTICS_ID
ARG GOOGLE_CLIENT_ID
ARG NUXT_ENV_GOOGLE_MAPS_API
ARG SENTRY_DSN
ARG SENTRY_ENVIRONMENT
ARG SENTRY_SAMPLE_RATE
ARG UPLOAD_FILE_SECRET
ARG URL_POTENCY_ARGICULTURE_FORM
ARG URL_POTENCY_EFISHERY_FORM
ARG VERSION_ENDPOINT
ARG SENTRY_ENABLED
ARG REDIRECT_URI
ARG APP_URL
ENV BASE_URL $BASE_URL
ENV GOOGLE_ANALYTICS_ID $GOOGLE_ANALYTICS_ID
ENV GOOGLE_CLIENT_ID $GOOGLE_CLIENT_ID
ENV NUXT_ENV_GOOGLE_MAPS_API $NUXT_ENV_GOOGLE_MAPS_API
ENV SENTRY_DSN $SENTRY_DSN
ENV SENTRY_ENVIRONMENT $SENTRY_ENVIRONMENT
ENV SENTRY_SAMPLE_RATE $SENTRY_SAMPLE_RATE
ENV UPLOAD_FILE_SECRET $UPLOAD_FILE_SECRET
ENV URL_POTENCY_ARGICULTURE_FORM $URL_POTENCY_ARGICULTURE_FORM
ENV URL_POTENCY_EFISHERY_FORM $URL_POTENCY_EFISHERY_FORM
ENV VERSION_ENDPOINT $VERSION_ENDPOINT
ENV SENTRY_ENABLED $SENTRY_ENABLED
ENV REDIRECT_URI $REDIRECT_URI
ENV APP_URL $APP_URL
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
